apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pg-operator
  namespace: argocd
spec:
  #goTemplate: true
  generators:
  - list:
      elements:
        - cluster: 'in-cluster'
          url: 'https://kubernetes.default.svc'
      template:
        metadata: {}
        spec:
          project: "default"
          source:
            repoURL: 'https://percona.github.io/percona-helm-charts/'
            helm: {}           
          destination: {}

  template:
    metadata:
      name: 'pg-operator'
    spec:
      project: "default"
      source:
        repoURL: 'https://percona.github.io/percona-helm-charts/'
        targetRevision: 1.2.0
        helm:            
          valueFiles:
            - values.yaml
        chart: pg-operator  
      destination:
        server: '{{url}}'
        namespace: percona
      syncPolicy: {}       
