apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
  namespace: argocd
spec:
  #goTemplate: true
  generators:
  - list:
      elements:
        - cluster: 'in-cluster'
          url: 'https://kubernetes.default.svc'
      template:
        metadata: {}
        spec:
          project: "default"
          source:
            repoURL: 'https://grafana.github.io/helm-charts'
            helm: {}
          destination: {}

  template:
    metadata:
      name: 'promtail'
    spec:
      project: "default"
      source:
        repoURL: 'https://grafana.github.io/helm-charts'
        targetRevision: 6.2.0
        helm:            
          valueFiles:
            - values.yaml
          values: |+
            serviceMonitor:
              # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
              enabled: true
              # -- Alternative namespace for ServiceMonitor resources
              namespace: monitoring
              # -- Namespace selector for ServiceMonitor resources
              namespaceSelector: {}
              # -- ServiceMonitor annotations
              annotations: {release: prometheus}
              # -- Additional ServiceMonitor labels
              labels: {release: prometheus, app: promtail}
              # -- ServiceMonitor scrape interval
              interval: 10s
              # -- ServiceMonitor scrape timeout in Go duration format (e.g. 15s)
              scrapeTimeout: 10s
        chart: promtail
      destination:
        server: '{{`{{url}}`}}'
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

