apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: 'in-cluster'
          url: 'https://kubernetes.default.svc'
      template:
        metadata: {}
        spec:
          project: "default"
          source:
            repoURL: 'https://charts.bitnami.com/bitnami'
            helm:
              parameters:
                - name: global.storageClass
                  value: local-path
                - name: master.persistence.storageClass
                  value: local-path
                - name: replica.persistence.storageClass
                  value: local-path
                - name: auth.enabled
                  value: 'false'
                - name: auth.sentinel
                  value: 'false'
                - name: replica.replicaCount
                  value: '1'
                - name: sentinel.persistence.storageClass
                  value: local-path
                - name: metrics.enabled
                  value: 'true'
                - name: metrics.serviceMonitor.enabled
                  value: 'true'
                - name: metrics.serviceMonitor.namespace
                  value: monitoring
                - name: metrics.prometheusRule.namespace
                  value: monitoring
                - name: metrics.prometheusRule.enabled
                  value: 'true'                  
          destination: {}

  template:
    metadata:
      name: 'redis'
    spec:
      project: "default"
      source:
        repoURL: 'https://charts.bitnami.com/bitnami'
        targetRevision: 17.0.5
        helm:            
          valueFiles:
            - values.yaml
        chart: redis
      destination:
        server: '{{`{{url}}`}}'
        namespace: redis
      syncPolicy:
        syncOptions:
          - CreateNamespace=true      
